### PR TITLE
Global weather plugin

### PR DESCRIPTION
**Pull request by bbookman**

### CODE REVIEW

**Comment by josancamon19** [comment]
I also don't see how this relates to doing smth with transcripts

**Comment by bbookman** [comment]
Journaling. As explained in another pull request there is currently no definition or boundaries as to what a hooligan should be. It seems that the user of the application should be free to choose what it means to be a plug-in. They can either choose to use it or not.

For example, right now you have no rule that says that the plug-in should avoid adult topics   

A plug-in could easily use the transcription and have some instruction that says convert this into a scene with a man and a woman making love

There are many many apps on the App Store that may appear to have little value, but they were still allowed in the App Store

**Comment by bbookman** [comment]
Again, I would suggest not closing a pull request. There is no harm with leaving a pull request open.

Every software organization I've ever worked for would not be closing a pull request like this

**Comment by bbookman** [comment]
They wouldn't be closing the request because that could lead to a loss of a valuable discussion

**Pull request closed without merging**
