### PR TITLE
Firebase Flavors Setup and Docs

### LINKED ISSUE #440: Improve App Setup Guide for Firebase
**Is your feature request related to a problem? Please describe.**
The currents setup guide for the app does not specify the steps to be taken to setup firebase for both the flavors

**Describe the solution you'd like**
Adding steps on how to setup Firebase for both prod and dev flavors. This guide should be written after some changes have been done in code (to allow multiple google-services.json files to support different flavors)

**Additional context**
https://pub.dev/packages/flutterfire_cli
https://firebase.google.com/docs/flutter/setup

### PR DESCRIPTION
**Pull request by mdmohsin7**
Closes #440 and #441

### CODE REVIEW

**Review by francip — APPROVED** [review]

**Comment by francip** [comment]
@josancamon19 this looks good to me. I tried the instructions, and it seems to configure everything correctly. I am unable to go past the login screen on Android through, which I don't think is a problem with @mdmohsin7 changes.

**Review by francip — COMMENTED** [review]
Looks like instructions might be missing a step or something. Sign in is failing with exception

```
E/flutter ( 8919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 8919): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919): #1      GoogleSignInAndroid._signInUserDataFromChannelData (package:google_sign_in_android/google_sign_in_android.dart:111:3)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919): #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919):
```

**Review by francip — CHANGES_REQUESTED** [review]
Looks like instructions might be missing a step or something. Sign in is failing with exception

```
E/flutter ( 8919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 8919): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919): #1      GoogleSignInAndroid._signInUserDataFromChannelData (package:google_sign_in_android/google_sign_in_android.dart:111:3)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919): #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
E/flutter ( 8919): <asynchronous suspension>
E/flutter ( 8919):
```

**Comment by mdmohsin7** [comment]
> Looks like instructions might be missing a step or something. Sign in is failing with exception
> 
> ```
> E/flutter ( 8919): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
> E/flutter ( 8919): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
> E/flutter ( 8919): <asynchronous suspension>
> E/flutter ( 8919): #1      GoogleSignInAndroid._signInUserDataFromChannelData (package:google_sign_in_android/google_sign_in_android.dart:111:3)
> E/flutter ( 8919): <asynchronous suspension>
> E/flutter ( 8919): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
> E/flutter ( 8919): <asynchronous suspension>
> E/flutter ( 8919): #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
> E/flutter ( 8919): <asynchronous suspension>
> E/flutter ( 8919):
> ```

Added a step in docs related to sha keys setup

**Review by francip — APPROVED** [review]

**Comment by francip** [comment]
I got it to work. @josancamon19 can you take a look at this as well?

**Comment by francip** [comment]
@mdmohsin7 PR#448 landed yesterday, it touches .gitignore. Can you merge it in your changes? To be honest, yours is better so feel free to fully override my changes.

**Review by josancamon19 — APPROVED** [review]

**Pull request merged**
