### PR TITLE
Buying Guide Cleanup

### PR DESCRIPTION
**Pull request by brianchilders**
I am proposing that the Buying Guide be cleaned up a bit to be more of a table format / listing the BOM.

I am also using this as an exercise to make sure that I follow the appropriate process - e.g. making a pull request into a branch instead of main.

I'm on Discord - so feel free to ping me on there if it makes more sense to discuss.  If I followed the process correctly, I'll take the same steps to update it with the new case and battery request.

### CODE REVIEW

**Comment by francip** [comment]
You need to pull and merge the latest from the main branch, and update the PR, so that it includes only your changes. As it is, there's ton of changes here that are unrelated to updating the buying guide, and if landed this will likely revert bunch of work.

**Comment by francip** [comment]
On a separate note, I wonder if we want to include the list of parts for OpenGlass as well...

**Comment by brianchilders** [comment]
Thank you for your comments @francip - I have changed the base branch to main.  I'm more than happy to also update OpenGlass documentation as well.  If this merge goes through successfully - I plan on updating the pictures in the assembly guide as I have the BOM needed with the updated battery.  I am also getting my 3d printer on Thursday and should be able to share updated visuals on the case.

**Comment by francip** [comment]
Your change accidentally lost the Next Step link at the bottom of the original document.

As a general suggestion, adding a screenshot of how your changes look helps reviewers understand better. Since BasedHardware site uses GitHub pages and Jekyll, you can find GitHub's instructions on how to test locally.

**Comment by francip** [comment]
Here's the link to how to test GH pages locally - https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

**Review by francip — APPROVED** [review]

**Pull request merged**
