### PR TITLE
feature:add share memory options

### PR DESCRIPTION
**Pull request by Wolfof420Street**
- Adding Share Memory Options

### CODE REVIEW

**Comment by josancamon19** [comment]
@Wolfof420Street Please upload a video displaying the feature, thanks

**Comment by Wolfof420Street** [comment]
here is the video. is this on track?  

https://github.com/BasedHardware/Friend/assets/47379369/dfe407a8-c554-4e90-b792-d007cdbfdd5b

**Comment by josancamon19** [comment]
Yes, seems good to me @Wolfof420Street

**Comment by josancamon19** [comment]
Please fix the formatting, use 
CleanShot 2024-07-07 at 11 36 56@2x

**Comment by josancamon19** [comment]
Please solve merge conflicts, and share a video of the current implementation, thanks @Wolfof420Street

**Comment by Wolfof420Street** [comment]
here is the current implementation . I have also fixed the merge conflicts. @josancamon19 

https://github.com/BasedHardware/Friend/assets/47379369/69be729b-d0aa-4ac8-9af4-5b5af16c2313

**Comment by josancamon19** [comment]
This is not doing what is supposed to do.
1. I don't see a similar UI as the one in the feature request.
2. Export summary should let you export in "markdown, pdf, plain text"
3. Export transcript same. (should have theinclude timestamps toggle)
4. Export audio should do what's shown.


It should also match the UI provided.
https://share.icloud.com/photos/0e8YhRG1jhIOvI3BKmj7D6beQ

**Comment by Wolfof420Street** [comment]
noted @josancamon19 . updating it shortly.

**Comment by Wolfof420Street** [comment]
hi @josancamon19 . this is the new implementation. 

https://github.com/user-attachments/assets/6e27198c-867a-46ae-94d5-a99ea2428e4a

**Review by josancamon19 — APPROVED** [review]

**Comment by josancamon19** [comment]
lgtm, but merging first to test directly on main.

**Pull request merged**
