### PR TITLE
Improve microphone recording

### PR DESCRIPTION
**Pull request by mdmohsin7**
Continuation for #348 

> There's a bug probably with long conversations, like caching not being cleared, random transcripts appearing that do not makes sense, or are from previous conversations, can you look into that? Yeah, @mdmohsin7, when you press stop, a ton of new transcription appear.

Yes those transcripts are of the audios which weren't processed. Our transcripts are ~15-30secs behind the audio being recorded. Improved the logic, now memory creation will be called only after the transcription of all files is complete.

> Also, when I restart the app, appears to still be recording.

On android or iOS? If it's on android then it is expected because our app will continue recording even when the app is closed completely. Can remove this behaviour if it isn't required

> It doesnt' seem to work either if I keep the app in the foreground on iOS.

This happened because someone removed `audio` from the `UIBackgroundModes` in plist file in some other commits.
@josancamon19

### CODE REVIEW

**Comment by josancamon19** [comment]
Hi @mdmohsin7 is this fully working and ready for review?

2. on android.

**Comment by mdmohsin7** [comment]
> Hi @mdmohsin7 is this fully working and ready for review?

Hi @josancamon19 yes it is. It should work without any issues hopefully.

> 2. on android.

Then the behaviour is expected because Android allows it as long as it isn't resource heavy. Should I remove this functionality?

**Comment by josancamon19** [comment]
Hi @mdmohsin7 doesn't seem to work with the server transcript, I think it's because of acc files, can we do wav?
Also, there's a bug, after finishing a conversation, a long one from e.g. a youtube video transcript, it displays some transcription text that was there before in a file or smth.

IMG_0005

Please move the code for this functionality to a separate file, as utils or mixin.
Finally, please merge back from main to your branch.

**Comment by josancamon19** [comment]
IMG_0006

Nothing in catpure page, after pressed stop transcribing this old transcript appeared.

**Comment by mdmohsin7** [comment]
> Hi @mdmohsin7 doesn't seem to work with the server transcript, I think it's because of acc files, can we do wav? 

@josancamon19 whisper is used on the server?

> Also, there's a bug, after finishing a conversation, a long one from e.g. a youtube video transcript it displays some transcription text that was there before in a file or smth.

Will add the functionality to delete previously recorded files before starting a fresh session. Also was the newly recorded content transcribed?

**Comment by mdmohsin7** [comment]
> Nothing in catpure page, after pressed stop transcribing this old transcript appeared.

It did not trigger the memory creation? Also did you get any errors or anything?

> after pressed stop transcribing this old transcript appeared.

The newly recorded audios aren't being transcribed?

**Comment by mdmohsin7** [comment]
Also @josancamon19 can you please share the `API_BASE_URL` on Email or DIscord DM so that I can test it with the server?

Also, if possible, can you share a temporary OpenAI API key so that I can test memory creation (for this and the location feature as well)? Free accounts don't have access to the 4o model through the API. I reached out to Nik on the 8th but haven't heard back yet, so I thought I would ask you.

**Comment by mdmohsin7** [comment]
> Hi @mdmohsin7 doesn't seem to work with the server transcript, I think it's because of acc files, can we do wav?

Changed from aac to wav, no major change was required for android. But for iOS, had to add the wav header for each file. Works with Deepgram, couldn't test with the server transcript as I don't have access to it.

> Also, there's a bug, after finishing a conversation, a long one from e.g. a youtube video transcript it displays some transcription text that was there before in a file or smth.

Fixed this, previous recording are deleted. Also fixed this occurrence after pressing stop recording.

> Nothing in capture page, after pressed stop transcribing this old transcript appeared.

memory creation was being triggered after default 120 seconds, will now trigger 10 seconds after all the files have been transcribed.

Tested the changes with long videos as well. Once I get the server endpoint, I'll test the changes again. I haven't pushed the code because there's some cleaning that has to be done.

**Comment by mdmohsin7** [comment]
Hi @josancamon19, I have pushed the refactored code with all the changes. I am also attaching a demo for both Android and iOS.

https://drive.google.com/drive/folders/1TCjPogFhyw51_JuvFryk_Phm_bN5wX0m

**Pull request merged**
