### PR TITLE
First cut of a Friend device simulator on macOS

### PR DESCRIPTION
**Pull request by ebariaux**

### CODE REVIEW

**Comment by diegoasua** [comment]
I was able to build and run the simulator on Mac and connected successfully to the iOS app but no transcripts came through

**Comment by ebariaux** [comment]
You need to press record on the simulator for sound to be sent over BLE.
Did you / can you enable sending the recordings to GCP ?
This would allow to check if sound is actually recorded, as I've read about several cases on no transcripts in Discord and that would help pinpoint where the problem is.

**Comment by diegoasua** [comment]
Gotcha transcripts coming through. LGTM. Separate device is less messy than incorporating this as a mock class inside Flutter app, I think your approach makes more sense than e.g. building a mock subclass and maintaining it

**Comment by diegoasua** [comment]
It would be great to write something about this in the README slash dev guide since I see it will be high usage?

**Comment by ebariaux** [comment]
Great, glad it worked.
I'll update the docs to reference this, busy week so it'll probably be in a few days.

**Comment by josancamon19** [comment]
lgtm :)

**Review by josancamon19 — APPROVED** [review]

**Comment by diegoasua** [comment]
While this initially worked for me, after re-installing the app the BLE scan service can't find the simulator. Why? Can you reproduce @ebariaux ?

**Comment by ebariaux** [comment]
Not sure which version of the app you're using.
The simulator uses the name of your Mac for advertising, this can't be changed.
Earlier version of the apps were scanning for a device name "Friend" (or "Super"), I made a PR to change that a scan based on service ID but this has been merged quite a while ago.

So one quick check you can do is renamed your Mac to "Friend" and see if that works.

**Comment by diegoasua** [comment]
Latest from App Store (1.0.6)

**Comment by diegoasua** [comment]
Can you try on your end reinstalling the app and scanning the mock device?

**Comment by ebariaux** [comment]
Not working for me either, because somebody changed the connection logic, see https://github.com/ebariaux/Friend/commit/ac95b8ae518665e132c9f9465a573d29407bfffa
that's filtering on Friend as the device name, that's what I was explaining above.
It's impossible for the Mac to advertise this name unless that's what you name your Mac.
But testing is a pain because there are caches in bluetooth stacks on both Mac and iOS device.

What's the reason of the above commit ? Is that fixing something ?

**Comment by diegoasua** [comment]
why is it filtering again by name when UUID filtering was implemented? @josancamon19 do you know?

**Pull request merged**
