### PR TITLE
Reminder app integration

### PR DESCRIPTION
**Pull request by diegoasua**

### CODE REVIEW

**Comment by diegoasua** [comment]
almost ready. Ironing out some details

**Comment by diegoasua** [comment]
BTW this PR also introduces the json-mode of the OpenAI API

will be hella useful for other calls to ensure JSON output

**Comment by diegoasua** [comment]
example snackbar:
<div align="center">
    
</div>

**Comment by diegoasua** [comment]
The integration is with the default calendar of the phone and requires no setting up, only granting permissions the first time the feature is turned on from settings.

In Android it will write to Google Calendar, in iOS to Apple Calendar. Reminders in the Google ecosystem are integrated into the Google Calendar, and in Apple starting with iOS 18 Apple Reminders are also part of Apple Calendar.

I have tested in iOS and works. Can someone test in Android?

**Comment by diegoasua** [comment]
Ready for a first pass @josancamon19

**Comment by josancamon19** [comment]
@diegoasua please relint with rules shared in the other PR so it's easy to see what was changed.

Also, record a video showing the feature in action please.

**Comment by diegoasua** [comment]
Will dm you video in discord

**Comment by josancamon19** [comment]
Closing PR, as I don't see significant progress, and reassigning ticket.

**Pull request closed without merging**
