### PR TITLE
Smart Reminder

### PR DESCRIPTION
**Pull request by raymanyyy**
Smart Reminder catches your verbal commitment and reminds you about them automatically. No manual scheduling required.
"I will check your report in an hour when I get to laptop".-- will schedule an app push notification "Check the report" in 60 minutes from when it was said.
Smart Reminder will process the commitment if you state what needs to be done and in what timeframe.

- smartReminder() and _init functions
- optional args for executeGptPrompt(): jsonResponseFormat and llmModelName
- cleanPrompt() and cleanResponse() helpers
- adjustments to createNotification() to be able to schedule notification

### CODE REVIEW

**Comment by josancamon19** [comment]
Hey @raymanyyy Looks awesome 👏

Before merging, could you please estimate how many requests would cost per user to execute this in a worst case scenario (24 hours?)

Thanks!

**Comment by raymanyyy** [comment]
# Cost estimation
Worst case scenario: "user talks all the time when they awake" - generating 100 tokens (75 eng words) per 2 minutes (cadence of the reminder run)

Will cost $0.36 per user per day (30 times per hour * 16 hours * $0.00075)
@josancamon19

**Comment by raymanyyy** [comment]
Added slider to enable/disable the feature like Coach

**Comment by josancamon19** [comment]
During testing got this issue
```
lutter: Battery level: 16
flutter: Subscribed to characteristic: 19b10001-e8f2-537e-4f6c-d104768a1214
flutter: Creating WAV file...
flutter: WAV file created: /var/mobile/Containers/Data/Application/9073055A-FDB1-42BC-B54D-481574038C6D/Documents/temp.wav
flutter: Response body: [{"end":19.694,"speaker":"SPEAKER_04","start":7.276,"text":" Then we are going to a different one, you know that, right?","is_user":false},{"end":22.178,"speaker":"SPEAKER_02","start":19.694,"text":"It's not on your calendar, it's open towards events.","is_user":false},{"end":23.7,"speaker":"SPEAKER_02","start":22.178,"text":"Remind me in one minute to check the news.","is_user":false}]
flutter: Creating WAV file...
flutter: WAV file created: /var/mobile/Containers/Data/Application/9073055A-FDB1-42BC-B54D-481574038C6D/Documents/temp.wav
flutter: Response body: []
flutter: Creating WAV file...
flutter: WAV file created: /var/mobile/Containers/Data/Application/9073055A-FDB1-42BC-B54D-481574038C6D/Documents/temp.wav
flutter: Response body: []
flutter: Smart Reminder Timer Triggered
flutter: _initiateSmartReminderTimer: Speaker 4: Then we are going to a different one, you know that, right?
flutter:
flutter: Speaker 2: It's not on your calendar, it's open towards events. Remind me in one minute to check the news.
flutter: executeGptPrompt response: {}
flutter: {}
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown:
flutter: type 'Null' is not a subtype of type 'String'
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      TranscriptWidgetState._initiateSmartReminderTimer.<anonymous closure> (package:friend_private/pages/capture/widgets/transcript.dart:245:16)
flutter: <asynchronous suspension>
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by josancamon19** [comment]
For the json output schema in the prompt let's do this:
```
class StructuredMemory(BaseModel):
    # title: str = Field(description="A title/name for this conversation", default='')
    # overview: str = Field(description="A brief overview of the conversation", default='')
    # action_items: List[str] = Field(description="A list of action items from the conversation", default=[])
    category: CategoryEnum = Field(description="A category for this memory", default=CategoryEnum.other)
    emoji: str = Field(description="An emoji to represent the memory", default='🧠')

    def __str__(self):
        action_item_str = '\n-'.join(self.action_items)
        return f"{self.title.capitalize()}\nOverview: {self.overview}\n{'Action items:' if len(self.action_items) else ''}\n{'-' if len(self.action_items) else ''}{action_item_str}".strip()


class Output(BaseModel):
    parsed: List[StructuredMemory]


parser = PydanticOutputParser(pydantic_object=Output)
print(parser.get_format_instructions())
```

Langchain generates a very nice format instructions.

Also @raymanyyy is it possiblle it detects multiple notifications, like an array of them?

**Comment by josancamon19** [comment]
Closing for now, thank you so much, but this will be delayed for now as we are trying to remove recurrent request to avoid draining battery and network :(

**Pull request closed without merging**
