### PR TITLE
Configure firmware to send audio as µ-law 16kHz

### PR DESCRIPTION
**Pull request by ebariaux**
IMPORTANT: this only changes things on firmware side.
Application needs to be adapted to support receiving this format.

### CODE REVIEW

**Review by francip — APPROVED** [review]

**Comment by francip** [comment]
Looks good, but I'd say we hold off on landing until we get the app-side changes ready as well.

**Comment by josancamon19** [comment]
why uLaw and not opus? @francip @ebariaux 

Is uLaw as good as opus or better?

**Comment by ebariaux** [comment]
@josancamon19 See https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=68103464 for more info

In theory Opus should be better but more difficult to get working and with heavier processing load

**Comment by francip** [comment]
Opus is definitely better than µ-law. However, it might be easier to start with µ-law on the app side for now.

**Comment by kodjima33** [comment]
@ebariaux can you send the audio quality file from u-law, compared to PCM?

**Comment by ebariaux** [comment]
@kodjima33 @josancamon19 
[Friend_PCMvsµLaw.zip](https://github.com/user-attachments/files/16008259/Friend_PCMvs.Law.zip)
Friend around my neck, in my office (so pretty quiet), me reciting some French text.
Using Friend firmware and my custom app for recording.

**Comment by josancamon19** [comment]
We don't support mulaw for now, and pcm and opus already supported. Closing this for now.

**Pull request closed without merging**
