### PR TITLE
Fix for Env late init issue due to insane Dart design

### PR DESCRIPTION
**Pull request by francip**
Details in https://discord.com/channels/1192313062041067520/1231903583717425153/1255280789399273482

### CODE REVIEW

**Comment by josancamon19** [comment]
The weird thing about this, is that noone else has had this issue @francip , could you share your `flutter doctor` results? thanks

**Comment by francip** [comment]
@josancamon19 

```
c:\src\Friend\apps\AppWithWearable>flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3810], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\Franci Penov\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Franci Penov\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Franci Penov\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0 Preview 1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.11.34909.67
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at C:\Users\Franci Penov\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • SM J327T (mobile) • 42004b4ee4626417 • android-arm    • Android 7.0 (API 24)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.3810]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 126.0.6478.126
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 126.0.2592.68

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by francip** [comment]
@josancamon19 here's my flutter version as well

```
c:\src\Friend\apps\AppWithWearable>flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (3 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

**Comment by josancamon19** [comment]
I think is more of a windows issue than a flutter issue, I will ask on discord if someone else has had this issue

**Comment by francip** [comment]
Updated the code to remove the multiple entry points and simplify the startup logic. Here's the Android startup now, but using flutter run and starting from the icon. Flavor is automatically determined, and the Env class is always initialized.

```
c:\Src\Friend\apps\AppWithWearable>flutter run --flavor dev
Launching lib\main.dart on SM J327T in debug mode...
Running Gradle task 'assembleDevDebug'...                          16.3s
✓ Built build\app\outputs\flutter-apk\app-dev-debug.apk
Installing build\app\outputs\flutter-apk\app-dev-debug.apk...        34.8s
I/flutter (27495): App flavor: dev
...
```

```
c:\Src\Friend\apps\AppWithWearable>flutter run --flavor prod
Launching lib\main.dart on SM J327T in debug mode...
Running Gradle task 'assembleProdDebug'...                         34.3s
✓ Built build\app\outputs\flutter-apk\app-prod-debug.apk
Installing build\app\outputs\flutter-apk\app-prod-debug.apk...        33.1s
I/flutter (28285): App flavor: prod
...
```

Start the app from the icon

```
c:\Src\Friend\apps\AppWithWearable>adb logcat -s flutter
07-01 14:10:46.490 29639 29686 I flutter : The Dart VM service is listening on http://127.0.0.1:50451/Uw_1CS8e85Y=/
07-01 14:10:48.138 29639 29668 I flutter : App flavor: prod
07-01 14:10:49.076 29639 29668 I flutter : initializeNotifications: true
...
```

**Review by josancamon19 — APPROVED** [review]

**Pull request merged**
