### PR TITLE
E2E OTA DFU

### PR DESCRIPTION
**Pull request by francip**
This is E2E OTA DFU skeleton.
The firmware changes are fully finalized.
The app changes include all the necessary logic to run successful OTA DFU, but need few improvements before being production ready:
1. No firmware version check
2. No instructions how to get the device to the point of being OTA ready (how to update bootloader and firmware manually to this version)
3. No downloading of firmware package
4. No proper state tracking for suppressing notification and reconnection attempts

### CODE REVIEW

**Comment by francip** [comment]
IMG_3810
IMG_3811

**Comment by francip** [comment]
To test:

1. Use firmware/bootloader/update-xiao_nrf52840_ble_sense_bootloader-0.9.0_nosd.uf2 to upgrade the board bootloader to v0.9.0
2. Build the new firmware and copy somewhere zephyr.uf2 as friend-1.0.3.uf2 for easier rollback during testing later.
3. Upload friend-1.0.3.uf2 to the board. Check with any BLE sniffer that the board now is showing Device Information Service with firmware revision set to v.1.0.3. 
4. Change the firmware revision in prj.conf to v1.0.4. Build and copy the new zephyr.hex as friend-1.0.4.hex.
5. Create a .zip from the .uf2 using the following command:
`adafruit-nrfutil dfu genpkg --dev-type 0x0052 --dev-revision 0xCE68 --application friend-1.0.4.hex friend-1.0.4.zip`
6. Copy the new .zip to apps/appwithwearable/assets/friend-1.0.4.zip
7. Modify apps/appwithwearable/pubspec.yaml to add the following line to the assets section:
`    - assets/friend-1.0.4.zip`
8. Modify apps/AppWithWearable/lib/pages/home/pages.dart to change startDfu call to:
`          await startDfu(_device!, 'assets/friend-1.0.4.zip', fileInAssets: true);`
9. Start the app and connect to the device
10. Press the Update firmware button. The device will switch to OTA DFU mode and the will blink rapid red light. The app will switch to Looking for the device page, but the
update will start in background. You can see update progress in the Flutter console.
11. When the update finishes, the device light will turn off. Reset the device to get it back into app mode, and verify with any BLE sniffer that the firmware revision is now v1.0.4.

Note: The app changes were tested with iOS only. We might need to tweak the Android-specific options in the startDfu implementation for Android.

**Comment by hlord2000** [comment]
Hello, have you considered using MCUboot instead of this? The Adafruit UF2 bootloader is only intended for applications using USB as the update path. UF2 stands for "USB flash format." Additionally, I'm not sure that the uf2 bootloader does any signing of images to confirm that images are valid before they are flashed.

**Comment by francip** [comment]
@hlord2000 I looked at MCUBoot, but I had a hard time making it work for Xiao Ble Sense. I'll keep looking at this, but at this point I'd rather us have a working solution even if not ideal.

Also, the Adafruit bootloader does support the Nordic legacy DFU service natively, not just UF2 updates.

**Comment by hlord2000** [comment]
https://github.com/hlord2000/Friend/tree/dev/mcuboot was able to get compiling here w/ latest Zephyr, still issues w/ booting. To build, use the following command: 
`west build -b xiao_ble/nrf52840/sense --sysbuild -p`

**Comment by francip** [comment]
@akshaynarisetti @Bentlybro can I get one of you to help go over this one again?

**Review by josancamon19 — APPROVED** [review]

**Pull request merged**
