### PR TITLE
created hardware buying guide docs

### PR DESCRIPTION
**Pull request by h0lai**
updated buying guide for docs

### CODE REVIEW

**Review by eng1n88r — APPROVED** [review]

**Comment by akshaynarisetti** [comment]
Could this be linked to the ReadMe, so people know the guide exists @h0lai

**Comment by holyr00d** [comment]
> Could this be linked to the ReadMe, so people know the guide exists @h0lai

I thought it the task was to move stuff out of readme into new docs/guides dir?

**Comment by after-ephemera** [comment]
@h0lai I think @akshaynarisetti was asking if you would kindly link to this doc _from_ the main readme so that people can make use of your contribution, thanks!

In other words, add a link possibly [here](https://github.com/BasedHardware/Friend/blob/main/README.md#hardware-buying-guide-20-total) with some text like "Click here for in-depth instructions"

**Comment by holyr00d** [comment]
ok i think i did that correctly...

**Comment by akshaynarisetti** [comment]
You should use jekyll

**Comment by after-ephemera** [comment]
@h0lai please pull the latest main and integrate your doc into the jekyll project [here](https://github.com/BasedHardware/Friend/tree/main/docs). If you need help getting started with Jekyll [their docs ](https://jekyllrb.com/)are pretty good.

**Pull request closed without merging**
