### PR TITLE
[Old] Include location of the memory

### LINKED ISSUE #384: Memories Include location of the memory ($100)
**Is your feature request related to a problem? Please describe.**
Location, should simply store Lat Lng of where the memory was created.

And should be displayed beautifully on the memory detail page, with a onClick to maps.

Sort of.
IMG_0001

- Update memory database object.
- Make this coordinates array, optional.
- If available display them on memory detail page.

### PR DESCRIPTION
**Pull request by mdmohsin7**
Closes #384
- Setup location service
- Enable multidex for debug
- Permission dialog
- Get location

### CODE REVIEW

**Comment by francip** [comment]
@mdmohsin7 might want to merge with the latest main, I landed yesterday a PR that enabled multidex.

**Comment by francip** [comment]
On a separate note, if the user does not grant location permission, can we infer location from the IP address? It's not going to be exact, and it's not going to be always correct, but it'll still be useful.

**Comment by josancamon19** [comment]
Yes, I was using this: https://ipapi.co/json

**Comment by mdmohsin7** [comment]
> @mdmohsin7 might want to merge with the latest main, I landed yesterday a PR that enabled multidex.

Oh! wasn't aware of it, will do

**Comment by mdmohsin7** [comment]
I couldn't fully test the functionality because I can't create memories yet. OpenAI's free account doesn't provide access to the 4o model through the API, and with other models, I always get the 'too many requests' error. Nik said he will share a key with me. As soon as I have it, I'll finish this feature.

I'll also be getting my hands on the Friend Dev Kit in 2-3 days.

**Comment by mdmohsin7** [comment]
> Yes, I was using this: https://ipapi.co/json

Should I implement this as well incase if the user denies the location permission forever?

**Comment by mdmohsin7** [comment]
Although I couldn't test with memories creation, but ideally it should work.


https://github.com/BasedHardware/Friend/assets/59914433/acb17567-3247-403f-b2a2-4818702eda0d

**Comment by mdmohsin7** [comment]
To show static map like the above one in the app, I've used one of the APIs of Google Maps. It generates a static map with the coordinates. Google Maps gives out $200 credits per month for free. So we shouldn't be incurring any cost till 100,000 calls for a month.
https://developers.google.com/maps/documentation/maps-static/usage-and-billing


https://github.com/user-attachments/assets/cb4e09e7-404c-45df-92a0-ced3dcf90cd1

**Pull request closed without merging**
